#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'src');
const DATA = path.join(ROOT, 'data');
const DIST = path.join(ROOT, 'dist');

const SITE_URL = (process.env.BASE_URL || 'https://malaysiastudenttools.com').replace(/\/$/, '');
const BASE_PATH = (process.env.BASE_PATH || '').replace(/\/$/, '');

const TEMPLATES = path.join(SRC, 'templates');
const LAYOUTS = path.join(TEMPLATES, 'layouts');
const PAGES = path.join(TEMPLATES, 'pages');
const PARTIALS = path.join(TEMPLATES, 'partials');

function readFile(filePath) { return fs.readFileSync(filePath, 'utf-8'); }

function writeFile(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf-8');
}

function copyDir(src, dest) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) { copyDir(srcPath, destPath); } 
    else { fs.copyFileSync(srcPath, destPath); }
  }
}

function cleanDist() {
  if (fs.existsSync(DIST)) { fs.rmSync(DIST, { recursive: true }); }
  fs.mkdirSync(DIST, { recursive: true });
}

function renderTemplate(template, vars) {
  return template.replace(/\{\{(\w+)\}\}/g, (match, key) => { return vars[key] !== undefined ? vars[key] : match; });
}

function loadPartials() {
  const partials = {};
  if (!fs.existsSync(PARTIALS)) return partials;
  for (const file of fs.readdirSync(PARTIALS)) {
    if (file.endsWith('.html')) {
      const name = path.basename(file, '.html');
      partials[name] = readFile(path.join(PARTIALS, file));
    }
  }
  return partials;
}

function wrapInLayout(content, vars) {
  const layoutPath = path.join(LAYOUTS, 'base.html');
  if (!fs.existsSync(layoutPath)) return content;
  const layout = readFile(layoutPath);
  return renderTemplate(layout, { ...vars, content });
}

function loadUniversityRegistry() { return JSON.parse(readFile(path.join(DATA, 'universities.json'))); }

function loadUniversityData(slug) {
  const filePath = path.join(DATA, 'universities', slug + '.json');
  if (!fs.existsSync(filePath)) return null;
  return JSON.parse(readFile(filePath));
}

function getVerifiedUniversities(registry) { return registry.universities.filter(u => u.status === 'verified'); }

function generateUniversityDataBundle(registry) {
  const dataMap = {};
  for (const uni of registry.universities) {
    const data = loadUniversityData(uni.slug);
    if (data && data.status === 'verified') dataMap[uni.slug] = data;
  }
  return [
    '// AUTO-GENERATED by build.js',
    '(function() { "use strict";',
    '  window.__UNIVERSITY_DATA__ = ' + JSON.stringify(dataMap, null, 2) + ';',
    '  window.__UNIVERSITY_REGISTRY__ = ' + JSON.stringify(registry.universities, null, 2) + ';',
    '})();'
  ].join('\n');
}

function generateGradingTableHTML(uniData) {
  const rule = uniData.academic_rules[0];
  if (!rule || !rule.grading_scales || rule.grading_scales.length === 0) return '<p>Grading table not available.</p>';
  const scale = rule.grading_scales[0];
  let rows = '';
  scale.grades.forEach(g => {
    const pointStr = (g.point !== null && g.point !== undefined) ? g.point.toFixed(2) : '-';
    let statusStr = '';
    if (g.counts.gpa && g.counts.cgpa && g.counts.credits) statusStr = 'Counted in GPA/CGPA';
    else if (g.counts.gpa && g.counts.credits) statusStr = 'Counted in GPA';
    else if (!g.counts.gpa && !g.counts.cgpa && !g.counts.credits) statusStr = 'Excluded (No credits)';
    else if (g.point === 0 && g.counts.credits) statusStr = 'Failed (Credits counted)';
    else statusStr = 'Excluded';
    rows += '<tr><td><strong>' + g.grade + '</strong></td><td>' + pointStr + '</td><td>' + statusStr + '</td></tr>\n';
  });
  return '<table class="table grading-table" style="width: 100%; text-align: left; border-collapse: collapse; margin-bottom: 1.5rem;"><thead><tr style="border-bottom: 2px solid #e2e8f0;"><th style="padding: 0.75rem;">Grade</th><th style="padding: 0.75rem;">Grade Point</th><th style="padding: 0.75rem;">Calculation Status</th></tr></thead><tbody>' + rows + '</tbody></table>';
}

function generateFAQ(uniData) {
  const shortName = uniData.short_name;
  const rule = uniData.academic_rules[0];
  const scale = rule.grading_scales && rule.grading_scales[0] ? rule.grading_scales[0] : null;
  let maxGPA = '4.00';
  if (scale) {
    const points = scale.grades.filter(g => typeof g.point === 'number').map(g => g.point);
    if (points.length > 0) maxGPA = Math.max(...points).toFixed(2);
  }
  let passFailStr = "Depending on the grading scale, non-standard grades like pass/withdraw may be excluded.";
  if (scale) {
    const excluded = scale.grades.filter(g => g.counts.gpa === false).map(g => g.grade);
    if (excluded.length > 0) {
      passFailStr = "Grades such as " + excluded.join(', ') + " do not contribute to your GPA or CGPA denominator.";
    }
  }
  const faqs = [
    { question: "What is the maximum GPA at " + shortName + "?", answer: "The maximum achievable Grade Point Average (GPA) for standard undergraduate programmes at " + shortName + " is " + maxGPA + "." },
    { question: "Are Pass/Fail or excluded grades counted in " + shortName + "'s CGPA?", answer: passFailStr },
    { question: "How does " + shortName + " calculate CGPA?", answer: "The Cumulative Grade Point Average (CGPA) is calculated by taking the sum of all quality points earned across all semesters, divided by the total number of credit hours attempted." }
  ];
  let html = '';
  faqs.forEach(f => {
    html += '<div class="faq-item" style="margin-bottom: 1.5rem;"><h3 style="font-size: 1.1rem; margin-bottom: 0.5rem; color: #1a1a2e;">' + f.question + '</h3><p style="margin-top: 0; color: #475569;">' + f.answer + '</p></div>\n';
  });
  return { faqs: faqs, html: html };
}

function generateUniversityListHTML(universities, basePath) {
  if (universities.length === 0) return '<p class="coming-soon">University calculators coming soon.</p>';
  const items = universities.map(u => '<a href="' + basePath + u.slug + '/" class="university-card"><span class="university-card__name">' + u.short_name + '</span><span class="university-card__full">' + u.name + '</span></a>');
  return '<div class="university-grid">' + items.join('\n') + '</div>';
}

function buildPage(templateName, vars, outputPath) {
  const templatePath = path.join(PAGES, templateName);
  if (!fs.existsSync(templatePath)) return;
  const rendered = renderTemplate(readFile(templatePath), vars);
  writeFile(path.join(DIST, outputPath), wrapInLayout(rendered, vars));
}

function build() {
  const startTime = Date.now();
  cleanDist();
  const registry = loadUniversityRegistry();
  const verified = getVerifiedUniversities(registry);
  const partials = loadPartials();
  const currentYear = new Date().getFullYear().toString();


  const GA4_MEASUREMENT_ID = process.env.GA4_MEASUREMENT_ID || '';
  let googleAnalyticsScript = '';
  if (GA4_MEASUREMENT_ID) {
    googleAnalyticsScript = `
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=${GA4_MEASUREMENT_ID}"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '${GA4_MEASUREMENT_ID}', { 'anonymize_ip': true });
  </script>
  <script src="${BASE_PATH}/js/analytics.js"></script>`;
  }

  const baseVars = {
    base_path: BASE_PATH,
    current_year: currentYear,
    og_image: SITE_URL + '/assets/favicon.svg',
    nav: renderTemplate(partials.nav || '', { base_path: BASE_PATH }),
    footer: renderTemplate(partials.footer || '', { current_year: currentYear, base_path: BASE_PATH }),
    google_analytics_script: googleAnalyticsScript,
  };

  writeFile(path.join(DIST, 'js', 'university-data.js'), generateUniversityDataBundle(registry));

  buildPage('home.html', { ...baseVars, title: 'Malaysia Student Tools', description: 'Free GPA calculator.', canonical: SITE_URL + '/', og_title: 'Malaysia Student Tools', og_description: 'Free GPA calculator.', og_url: SITE_URL + '/', university_list_html: generateUniversityListHTML(verified, BASE_PATH + '/gpa-calculator/') }, 'index.html');
  
  buildPage('gpa-calculator.html', { ...baseVars, title: 'GPA Calculator', description: 'GPA Calculator.', canonical: SITE_URL + '/gpa-calculator/', og_title: 'GPA Calculator', og_description: 'GPA Calculator.', og_url: SITE_URL + '/gpa-calculator/', university_list_html: generateUniversityListHTML(verified, BASE_PATH + '/gpa-calculator/') }, 'gpa-calculator/index.html');
  
  buildPage('cgpa-calculator.html', { ...baseVars, title: 'CGPA Calculator', description: 'CGPA Calculator.', canonical: SITE_URL + '/cgpa-calculator/', og_title: 'CGPA Calculator', og_description: 'CGPA Calculator.', og_url: SITE_URL + '/cgpa-calculator/', university_list_html: generateUniversityListHTML(verified, BASE_PATH + '/cgpa-calculator/') }, 'cgpa-calculator/index.html');
  buildPage('wam-calculator.html', { ...baseVars, title: 'WAM Calculator', description: 'WAM Calculator.', canonical: SITE_URL + '/wam-calculator/', og_title: 'WAM Calculator', og_description: 'WAM Calculator.', og_url: SITE_URL + '/wam-calculator/', university_list_html: generateUniversityListHTML(verified.filter(u => {
    const d = loadUniversityData(u.slug);
    return d && d.academic_rules[0] && d.academic_rules[0].calculation_methods && d.academic_rules[0].calculation_methods.primary && d.academic_rules[0].calculation_methods.primary.method === 'weighted_mark_average';
  }), BASE_PATH + '/wam-calculator/') }, 'wam-calculator/index.html');

  for (const uni of verified) {
    const uniData = loadUniversityData(uni.slug);
    if (!uniData) continue;
    let sourcesHtml = uniData.sources && uniData.sources.length > 0 ? '<ul class="source-list">' + uniData.sources.map(s => '<li><a href="' + s.url + '" target="_blank">' + s.title + '</a><br><small>Verified: ' + s.verified_date + '</small></li>').join('') + '</ul>' : '<p>Official sources pending.</p>';
    const faqData = generateFAQ(uniData);
    const schemaOrg = { "@context": "https://schema.org", "@graph": [ { "@type": "WebApplication", "name": uni.short_name + ' GPA & CGPA Calculator', "applicationCategory": "EducationalApplication", "operatingSystem": "Any", "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" } }, { "@type": "FAQPage", "mainEntity": faqData.faqs.map(f => ({ "@type": "Question", "name": f.question, "acceptedAnswer": { "@type": "Answer", "text": f.answer } })) } ] };
    const scopeExcludes = uniData.scopes[0] && uniData.scopes[0].excludes ? uniData.scopes[0].excludes.join(', ') : '';

    const uniVars = {
      ...baseVars,
      university_name: uni.short_name,
      university_short_name: uni.short_name,
      university_full_name: uni.name,
      university_slug: uni.slug,
      university_data_json: JSON.stringify(uniData),
      sources_html: sourcesHtml,
      grading_table_html: generateGradingTableHTML(uniData),
      faq_html: faqData.html,
      scope_warning_text: 'This calculator applies to ' + (uniData.scopes[0].programmes[0] || 'standard programmes') + '. Excludes: ' + (scopeExcludes || 'None specified') + '.',
      schema_org_json: JSON.stringify(schemaOrg, null, 2)
    };

    const calcMethods = uniData.academic_rules[0] && uniData.academic_rules[0].calculation_methods ? uniData.academic_rules[0].calculation_methods : {};
    if (calcMethods.primary && calcMethods.primary.method === 'weighted_mark_average') {
      buildPage('wam-university.html', { ...uniVars, title: uni.short_name + ' WAM Calculator', description: 'WAM Calculator.', canonical: SITE_URL + '/wam-calculator/' + uni.slug + '/', og_title: uni.short_name + ' WAM Calculator', og_description: 'WAM Calculator.', og_url: SITE_URL + '/wam-calculator/' + uni.slug + '/' }, 'wam-calculator/' + uni.slug + '/index.html');
    } else {
      buildPage('gpa-university.html', { ...uniVars, title: uni.short_name + ' GPA Calculator', description: 'GPA Calculator.', canonical: SITE_URL + '/gpa-calculator/' + uni.slug + '/', og_title: uni.short_name + ' GPA Calculator', og_description: 'GPA Calculator.', og_url: SITE_URL + '/gpa-calculator/' + uni.slug + '/' }, 'gpa-calculator/' + uni.slug + '/index.html');
      buildPage('cgpa-university.html', { ...uniVars, title: uni.short_name + ' CGPA Calculator', description: 'CGPA Calculator.', canonical: SITE_URL + '/cgpa-calculator/' + uni.slug + '/', og_title: uni.short_name + ' CGPA Calculator', og_description: 'CGPA Calculator.', og_url: SITE_URL + '/cgpa-calculator/' + uni.slug + '/' }, 'cgpa-calculator/' + uni.slug + '/index.html');
    }
  }

  copyDir(path.join(SRC, 'css'), path.join(DIST, 'css'));
  copyDir(path.join(SRC, 'assets'), path.join(DIST, 'assets'));
  copyDir(path.join(SRC, 'js'), path.join(DIST, 'js'));

  if (fs.existsSync(path.join(ROOT, 'google4d56b8e2f6526595.html'))) {
    fs.copyFileSync(path.join(ROOT, 'google4d56b8e2f6526595.html'), path.join(DIST, 'google4d56b8e2f6526595.html'));
  }

  if (!GA4_MEASUREMENT_ID) {
    if (fs.existsSync(path.join(DIST, 'js', 'analytics.js'))) fs.unlinkSync(path.join(DIST, 'js', 'analytics.js'));
  }

  const sitemapUrls = ['/', '/gpa-calculator/', '/cgpa-calculator/', '/wam-calculator/'];
  verified.forEach(u => {
    const data = loadUniversityData(u.slug);
    if (!data) return;
    const rule = data.academic_rules[0];
    const calc = rule && rule.calculation_methods ? rule.calculation_methods : {};
    
    if (calc.gpa) {
      sitemapUrls.push('/gpa-calculator/' + u.slug + '/');
      sitemapUrls.push('/cgpa-calculator/' + u.slug + '/');
    }
    if (calc.primary && calc.primary.method === 'weighted_mark_average') {
      sitemapUrls.push('/wam-calculator/' + u.slug + '/');
    }
  });
  let sitemapXml = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';
  sitemapUrls.forEach(u => { sitemapXml += '  <url>\n    <loc>' + SITE_URL + u + '</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n'; });
  sitemapXml += '</urlset>';
  writeFile(path.join(DIST, 'sitemap.xml'), sitemapXml);
  writeFile(path.join(DIST, 'robots.txt'), 'User-agent: *\nAllow: /\n\nSitemap: ' + SITE_URL + '/sitemap.xml\n');
  console.log('Build complete.');
}
build();
